name: "mobility_dbt"
version: "1.0.0"
config-version: 2

profile: "mobility_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mobility_dbt:
    staging:
      +schema: STAGING
      +materialized: view
      +tags: ["staging"]
    core:
      +schema: CORE
      +materialized: table
      +tags: ["core"]
    marts:
      +schema: MART
      +materialized: table
      +tags: ["mart"]